// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_follows.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
With inserted_feed_follow as (
    INSERT INTO feed_follows (id, created_at, updated_at, user_id, feed_id)
    VALUES (
        $1,
        $2,
        $3,
        $4,
        $5
    )
    returning id, created_at, updated_at, user_id, feed_id
)
select 
    iff.id, iff.created_at, iff.updated_at, iff.user_id, iff.feed_id,
    u.name as user_name,
    f.name as feed_name
from inserted_feed_follow iff
join users u on u.id = iff.user_id
join feeds f on f.id = iff.feed_id
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

type CreateFeedFollowRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	UserID    uuid.UUID
	FeedID    uuid.UUID
	UserName  string
	FeedName  string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
		&i.UserName,
		&i.FeedName,
	)
	return i, err
}

const getFeedFollowsForUser = `-- name: GetFeedFollowsForUser :many
select 
    f.name as feed_name,
    u.name as user_name,
    f.url as url,
    fc.name as feed_creator
from feed_follows ff
join users u on u.id = ff.user_id
join feeds f on f.id = ff.feed_id
join users fc on f.user_id = fc.id
where ff.user_id = $1
order by f.name asc
`

type GetFeedFollowsForUserRow struct {
	FeedName    string
	UserName    string
	Url         string
	FeedCreator string
}

func (q *Queries) GetFeedFollowsForUser(ctx context.Context, userID uuid.UUID) ([]GetFeedFollowsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedFollowsForUserRow
	for rows.Next() {
		var i GetFeedFollowsForUserRow
		if err := rows.Scan(
			&i.FeedName,
			&i.UserName,
			&i.Url,
			&i.FeedCreator,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFeedFollowForUser = `-- name: RemoveFeedFollowForUser :exec
delete from feed_follows
where user_id = $1 and feed_id = $2
`

type RemoveFeedFollowForUserParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) RemoveFeedFollowForUser(ctx context.Context, arg RemoveFeedFollowForUserParams) error {
	_, err := q.db.ExecContext(ctx, removeFeedFollowForUser, arg.UserID, arg.FeedID)
	return err
}
